let mouse={x:0,y:0};function drawGhost(){const t=TYPES[state.buildType],s=42*t.size,ok=canPlace(mouse.x,mouse.y,t.size);ctx.globalAlpha=.65;roundRect(mouse.x-s/2,mouse.y-s/2,s,s,13,ok?t.color:'#ff5f5f');ctx.globalAlpha=1;ctx.font=`${Math.max(22,s*.38)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.emoji,mouse.x,mouse.y);}
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top};});
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(state.buildType){place(state.buildType,x,y);return;}const hit=[...state.buildings].reverse().find(b=>Math.abs(x-b.x)<42*b.size/2&&Math.abs(y-b.y)<42*b.size/2);state.selected=hit?hit.id:null;renderInspector();});
function needStatus(value,good=35,warn=58){return value<good?'good':value<warn?'warn':'bad';}
function updateUI(){
 $('#cash').textContent=money(state.cash);$('#visitors').textContent=state.guests.length;$('#rating').textContent=Math.round(state.rating)+'%';$('#profit').textContent=(state.dayProfit>=0?'+':'')+money(state.dayProfit);$('#profit').style.color=state.dayProfit>=0?'var(--mint)':'var(--red)';
 const rows=[['😊','Happiness',state.rating,100-state.rating],['🍔','Hunger',100-state.metrics.hungry,state.metrics.hungry],['🥤','Thirst',100-state.metrics.thirsty,state.metrics.thirsty],['🚻','Restroom',100-state.metrics.toilet,state.metrics.toilet]];
 $('#healthPanel').innerHTML=rows.map(([i,n,p,bad])=>`<div class="health-row"><span>${i}</span><div><span>${n}</span><div class="bar"><i style="width:${clamp(p,0,100)}%"></i></div></div><b class="${needStatus(bad)}">${Math.round(p)}%</b></div>`).join('');
 renderAlerts();
 if(state.mission===0){$('#missionTitle').textContent='Grow your first crowd';$('#missionText').textContent='Reach 25 visitors and maintain a 70% rating. Reward: $800';}else if(state.mission===1){$('#missionTitle').textContent='Build a profitable destination';$('#missionText').textContent='Earn $3,000 in lifetime revenue. Reward: $1,500';}else{$('#missionTitle').textContent='Tycoon mode unlocked';$('#missionText').textContent=`Day ${state.day} • Keep expanding and chase a 95% park rating.`;}
}
function renderAlerts(){const a=[];const count=k=>state.buildings.filter(b=>TYPES[b.type].kind===k).length;const qmax=kind=>Math.max(0,...state.buildings.filter(b=>TYPES[b.type].kind===kind).map(b=>b.queue.length));
 if(state.metrics.hungry>57)a.push({icon:'🍔',title:'Guests are getting hungry',text:count('food')?'Add another food stand or upgrade service.':'Your park has no food shop.',type:'burger',critical:state.metrics.hungry>75});
 if(state.metrics.thirsty>55)a.push({icon:'🥤',title:'Not enough drinks',text:count('drink')?'Drink queues cannot keep up.':'Build a drink kiosk near busy rides.',type:'drinks',critical:state.metrics.thirsty>75});
 if(state.metrics.toilet>54)a.push({icon:'🚻',title:'Restrooms are overloaded',text:count('toilet')?'Add stalls or another restroom.':'Guests urgently need a restroom.',type:'restroom',critical:state.metrics.toilet>75});
 const overloaded=state.buildings.find(b=>TYPES[b.type].kind==='ride'&&b.queue.length>b.capacity*2);if(overloaded)a.push({icon:'🪑',title:`${TYPES[overloaded.type].name} queue is too long`,text:`${overloaded.queue.length} guests waiting. Add seats from the inspector.`,select:overloaded.id,critical:false});
 if(!state.buildings.some(b=>TYPES[b.type].kind==='ride'))a.push({icon:'🎢',title:'No attractions!',text:'Build a ride to draw visitors into your park.',type:'carousel',critical:true});
 $('#alerts').innerHTML=a.slice(0,3).map((x,i)=>`<div class="alert ${x.critical?'critical':''}"><div class="aicon">${x.icon}</div><div><b>${x.title}</b><span>${x.text}</span></div><button data-alert="${i}">${x.select?'View':'Build'}</button></div>`).join('');
 document.querySelectorAll('[data-alert]').forEach(btn=>btn.onclick=()=>{const x=a[+btn.dataset.alert];if(x.select){state.selected=x.select;renderInspector();}else setBuildMode(x.type);});
}
function renderInspector(){const b=state.buildings.find(x=>x.id===state.selected);if(!b){$('#inspector').innerHTML='<div class="panel-card empty">Select a ride, shop, or restroom to see its performance and upgrade options.</div>';return;}const t=TYPES[b.type];const qState=b.queue.length>b.capacity*2?'bad':b.queue.length>b.capacity?'warn':'good';
 const upgrades=t.kind==='ride'?[['🪑','More seats',`Capacity ${b.capacity} → ${b.capacity+2}`,upgradeCost(b,'capacity'),'capacity'],['⚡','Faster cycle',`${b.cycle.toFixed(1)}s → ${Math.max(3,b.cycle*.88).toFixed(1)}s`,upgradeCost(b,'speed'),'speed'],['✨','Better theming',`Appeal ${Math.round(b.appeal)} → ${Math.round(b.appeal+10)}`,upgradeCost(b,'appeal'),'appeal']]:[['👥','More service spots',`Capacity ${b.capacity} → ${b.capacity+1}`,upgradeCost(b,'capacity'),'capacity'],['⚡','Faster service',`${b.cycle.toFixed(1)}s → ${Math.max(1.4,b.cycle*.82).toFixed(1)}s`,upgradeCost(b,'speed'),'speed'],['✨','Premium design',`Appeal ${Math.round(b.appeal)} → ${Math.round(b.appeal+6)}`,upgradeCost(b,'appeal'),'appeal']];
 $('#inspector').innerHTML=`<div class="panel-card"><div class="selected-head"><div class="selected-icon">${t.emoji}</div><div><h2>${t.name}</h2><p>Level ${b.level} ${t.kind==='ride'?'attraction':'facility'}</p></div></div></div><div class="panel-card"><div class="metric-row"><span>Current queue</span><b class="${qState}">${b.queue.length} guests</b></div><div class="metric-row"><span>Capacity</span><b>${b.capacity}</b></div><div class="metric-row"><span>Cycle time</span><b>${b.cycle.toFixed(1)} sec</b></div><div class="metric-row"><span>Guests served</span><b>${b.served}</b></div><div class="metric-row"><span>Total revenue</span><b>${money(b.revenue)}</b></div></div><div class="section-title">Upgrades</div><div class="panel-card">${upgrades.map(u=>`<button class="upgrade" data-upgrade="${u[4]}" ${state.cash<u[3]?'disabled':''}><div class="uicon">${u[0]}</div><div><b>${u[1]}</b><span>${u[2]}</span></div><em>${money(u[3])}</em></button>`).join('')}</div>`;
 document.querySelectorAll('[data-upgrade]').forEach(btn=>btn.onclick=()=>upgrade(b.id,btn.dataset.upgrade));}
function upgradeCost(b,kind){const base=kind==='capacity'?TYPES[b.type].cost*.42:kind==='speed'?TYPES[b.type].cost*.34:TYPES[b.type].cost*.28;return Math.round(base*Math.pow(1.38,b.level-1)/10)*10;}
function upgrade(id,kind){const b=state.buildings.find(x=>x.id===id);if(!b)return;const cost=upgradeCost(b,kind);if(state.cash<cost)return toast('Not enough cash');state.cash-=cost;if(kind==='capacity')b.capacity+=TYPES[b.type].kind==='ride'?2:1;if(kind==='speed')b.cycle=Math.max(TYPES[b.type].kind==='ride'?3:1.4,b.cycle*(TYPES[b.type].kind==='ride'?.88:.82));if(kind==='appeal')b.appeal+=TYPES[b.type].kind==='ride'?10:6;b.level++;burst(b.x,b.y,'#ffd166');toast(`${TYPES[b.type].name} upgraded`);renderInspector();}
