function removeFromQueues(g){state.buildings.forEach(b=>{b.queue=b.queue.filter(id=>id!==g.id);b.active=b.active.filter(id=>id!==g.id);});}
function updateBuildings(dt){for(const b of state.buildings){b.timer-=dt;if(b.timer<=0){if(b.active.length){for(const id of b.active){const g=state.guests.find(x=>x.id===id);if(!g)continue;finishService(g,b);}b.active=[];}
   const count=Math.min(b.capacity,b.queue.length);if(count>0){const ids=b.queue.splice(0,count);b.active=ids;b.timer=b.cycle;for(const id of ids){const g=state.guests.find(x=>x.id===id);if(g){g.status='using';g.wait=0;chargeGuest(g,b);}}}
  }
  state.cash-=b.upkeep*dt/10;state.dayProfit-=b.upkeep*dt/10;
 }}
function chargeGuest(g,b){const t=TYPES[b.type];const paid=Math.min(g.money,b.price);g.money-=paid;state.cash+=paid;state.dayProfit+=paid;state.lifetimeProfit+=paid;b.revenue+=paid;floating(b.x,b.y-25,'+'+money(paid));}
function finishService(g,b){const kind=TYPES[b.type].kind;if(kind==='ride'){g.fun=clamp(g.fun+48+b.appeal*.2,0,100);g.happiness=clamp(g.happiness+9,0,100);g.thought='🤩';}if(kind==='food'){g.hunger=clamp(g.hunger-72,0,100);g.thirst+=8;g.happiness+=4;g.thought='😋';}if(kind==='drink'){g.thirst=clamp(g.thirst-78,0,100);g.toilet+=14;g.happiness+=3;g.thought='🥤';}if(kind==='toilet'){g.toilet=0;g.happiness+=7;g.thought='😌';}if(kind==='rest'){g.happiness+=14;g.fun+=6;g.thought='😊';}b.served++;g.status='wandering';g.target=null;g.tx=rand(40,W-40);g.ty=rand(90,H-70);g.wait=0;}
function updateMetrics(){const n=Math.max(1,state.guests.length);const avg=k=>state.guests.reduce((s,g)=>s+g[k],0)/n;state.metrics={hungry:avg('hunger'),thirsty:avg('thirst'),toilet:avg('toilet'),bored:100-avg('fun')};const happy=avg('happiness');const queues=state.buildings.reduce((s,b)=>s+b.queue.length,0);state.rating=clamp(happy-queues/Math.max(1,state.guests.length)*6+state.buildings.reduce((s,b)=>s+b.appeal,0)/30,0,100);}
function update(dt){if(state.paused||!state.started)return;dt*=state.speed;state.time+=dt;state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnGuest();const pull=state.buildings.reduce((s,b)=>s+b.appeal,0);state.spawnTimer=clamp(6-pull/100-state.rating/50,1.0,6);}updateGuests(dt);updateBuildings(dt);updateParticles(dt);updateMetrics();state.autosave+=dt;if(state.autosave>20){save(false);state.autosave=0;}if(state.time>90){state.day++;state.time=0;state.dayProfit=0;toast(`Day ${state.day} begins`);}updateMission();}
function updateMission(){if(state.mission===0&&state.guests.length>=25&&state.rating>=70){state.cash+=800;state.mission=1;toast('Mission complete: +$800');}if(state.mission===1&&state.lifetimeProfit>=3000){state.cash+=1500;state.mission=2;toast('Mission complete: +$1,500');}}
function burst(x,y,color){for(let i=0;i<18;i++)state.particles.push({x,y,vx:rand(-55,55),vy:rand(-80,-20),life:1,color});}
function floating(x,y,text){state.floatingText.push({x,y,text,life:1});}
function updateParticles(dt){for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt;p.life-=dt;}state.particles=state.particles.filter(p=>p.life>0);for(const f of state.floatingText){f.y-=18*dt;f.life-=dt;}state.floatingText=state.floatingText.filter(f=>f.life>0);}
function draw(){ctx.clearRect(0,0,W,H);drawGround();drawPaths();for(const b of state.buildings)drawBuilding(b);drawGuests();drawEffects();if(state.buildType)drawGhost();}
function drawGround(){const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#9be382');grad.addColorStop(1,'#72c86b');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.12;ctx.fillStyle='#2c7b4c';for(let x=12;x<W;x+=26)for(let y=12;y<H;y+=26)ctx.fillRect(x+(y%52?8:0),y,2,7);ctx.globalAlpha=1;for(let i=0;i<14;i++){const x=(i*137)%W,y=80+(i*89)%(H-150);ctx.fillStyle='#4cab60';ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#35894a';ctx.fillRect(x-2,y+4,4,12);}}
function drawPaths(){ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#d9c69b';ctx.lineWidth=34;ctx.beginPath();ctx.moveTo(state.gate.x,H+10);ctx.lineTo(state.gate.x,H*.68);for(const b of state.buildings){ctx.moveTo(state.gate.x,H*.68);ctx.quadraticCurveTo(state.gate.x,b.y,b.x,b.y);}ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=3;ctx.setLineDash([8,10]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#263a4b';ctx.fillRect(state.gate.x-42,H-25,84,25);ctx.fillStyle='#ffe27a';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText('ENTRANCE',state.gate.x,H-8);}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function drawBuilding(b){const t=TYPES[b.type],s=42*b.size;ctx.save();ctx.translate(b.x,b.y);ctx.shadowColor='rgba(0,0,0,.24)';ctx.shadowBlur=16;ctx.shadowOffsetY=8;roundRect(-s/2,-s/2,s,s,13,t.color);ctx.shadowColor='transparent';ctx.strokeStyle=state.selected===b.id?'#fff':'rgba(8,30,42,.25)';ctx.lineWidth=state.selected===b.id?4:2;ctx.stroke();ctx.fillStyle='rgba(255,255,255,.25)';roundRect(-s/2+7,-s/2+7,s-14,11,6,'rgba(255,255,255,.28)');ctx.font=`${Math.max(22,s*.38)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.emoji,0,2);ctx.fillStyle='#082033';ctx.font='900 10px system-ui';ctx.fillText(`Lv ${b.level}`,0,s/2-10);ctx.restore();if(b.queue.length){ctx.fillStyle=b.queue.length>b.capacity*2?'#ff6161':'#172b3a';roundRect(b.x+s/2-14,b.y-s/2-12,30,22,10,ctx.fillStyle);ctx.fillStyle='white';ctx.font='900 10px system-ui';ctx.textAlign='center';ctx.fillText(b.queue.length,b.x+s/2+1,b.y-s/2+3);}if(b.active.length){const p=clamp(1-b.timer/b.cycle,0,1);ctx.strokeStyle='rgba(8,32,51,.25)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(b.x,b.y,s*.48,-Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.strokeStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,s*.48,-Math.PI/2,-Math.PI/2+p*Math.PI*2);ctx.stroke();}}
function drawGuests(){for(const g of state.guests){ctx.save();ctx.translate(g.x,g.y);ctx.fillStyle='rgba(0,0,0,.15)';ctx.beginPath();ctx.ellipse(0,8,8,3,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=g.shirt;roundRect(-5,-2,10,13,4,g.shirt);ctx.fillStyle=g.color;ctx.beginPath();ctx.arc(0,-6,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17212b';ctx.beginPath();ctx.arc(-2,-7,1,0,Math.PI*2);ctx.arc(2,-7,1,0,Math.PI*2);ctx.fill();ctx.restore();if(g.thought){ctx.font='15px system-ui';ctx.fillText(g.thought,g.x+7,g.y-13);if(Math.random()<.01)g.thought='';}}}
function drawEffects(){for(const p of state.particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4);}for(const f of state.floatingText){ctx.globalAlpha=f.life;ctx.fillStyle='#fff';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);}ctx.globalAlpha=1;}
